language: cpp
script: cmake . && make
addons:
 apt:
   packages:
   - cmake # v2.8 or higher
   - make
   - gcc # or clang-7
   # i386
   - gcc-multilib # cross-compile 32-bit applications on 64-bit systems
   - nasm
   - multiboot
   - grub-common # contains grub-file to verify Multiboot compliance
   # native
   # javascript
   - valgrind
   # vm.sh
   - grub-common # contains grub-mkrescue to build a bootable ISO
   - grub-pc-bin # PC/BIOS architecture version of GRUB (eg. non-UEFI)
   - mtools # symlinked from mformat, needed by grub-mkrescue
   - xorriso # create ISO files, needed by grub-mkrescue
   # VirtualBox
