language: cpp
script: cmake . && make
addons:
 apt:
   packages:
   - cmake
   - make
   - g++
   # i386
   - nasm
   - multiboot
   - g++-multilib # cross-compile 32-bit applications on 64-bit systems
   # vm.sh
   - grub-common # contains grub-mkrescue
   - grub-pc-bin # PC/BIOS architecture version of GRUB (eg. non-UEFI)
   - mtools # symlinked from mformat, needed by grub-mkrescue
   - xorriso # create ISO files, needed by grub-mkrescue
   # - VirtualBox
