language: c

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake # v2.8 or higher
      - make
      # x86-32
      - gcc-multilib # cross-compile 32-bit applications on 64-bit systems
      - nasm
      - multiboot
      - grub-common # contains grub-file to verify Multiboot compliance

before_script:
  - mkdir build/ && cd build/

script:
  - cmake "$TRAVIS_BUILD_DIR" && cmake --build .
