# Travis CI build config
# https://config.travis-ci.com

language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

env:
  - BUILD_NAME=NATIVE BUILD_TYPE=Debug
  - BUILD_NAME=NATIVE BUILD_TYPE=Release
  - BUILD_NAME=X86_32 BUILD_TYPE=Debug
  - BUILD_NAME=X86_32 BUILD_TYPE=Release

addons:
  apt:
    packages:
      # Target: all
      - cmake
      - make

      # Target: x86-32
      - nasm # Assembler
      - multiboot # Multiboot header files and `grub-file` to verify compliance

      # Target: x86-32, Script: iso.sh
      - grub-common
      - xorriso

      # Target: x86-32, Script: vm.sh
      # https://www.virtualbox.org/wiki/Linux_Downloads

      # Target: x86-32, Host: Linux 64-bit
      - gcc-multilib # cross-compile 32-bit applications on 64-bit systems

script:
  - cmake "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DBUILD_$BUILD_NAME=ON" "$TRAVIS_BUILD_DIR"
  - cmake --build .

notifications:
  email:
    on_success: always
