.POSIX:

OBJ=.o
LIB=.a
LIBPREFIX=lib
EXE=
LDOUT=-o
AROUT=
CCNAME=$(CC)
CCCONFIG=../Makefile.$(CCNAME)

# Workaround for include-line support on both `make` and `nmake`.
#\
!INCLUDE $(CCCONFIG) #\
!IF 0
-include $(CCCONFIG) #\
!ENDIF
